version: '3'

services:
  database:
    platform: linux/x86_64
    container_name: database
    build: ./image
    ports:
      - 4306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "hs_reservation"
