version: '3'

services:
  database:
    container_name: database
    image: mysql
    ports:
      - 4306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "hs-reservation"
